#!/usr/bin/env bash
# Auto-run remaining experiments + eval + push to GitHub
# Runs in background, logs to /data/lab/KDD2027_LLM/experiments/auto_pipeline.log
set -e

REPO=/data/lab/KDD2027_LLM
cd "$REPO"
export OPENAI_API_KEY=sk-9ZuUA9MWpglHgMJhKyBsPUDnGDm95ygy9yN4YqVoLc7GsRp0
LOG="$REPO/experiments/auto_pipeline.log"
GH_USER="llmnjust-afk"
GH_TOKEN="$1"   # pass token as arg

echo "========================================" | tee -a "$LOG"
echo "[$(date)] Auto pipeline started" | tee -a "$LOG"

# --- Wait for any running python experiment processes ---
echo "[$(date)] Waiting for running experiments to finish..." | tee -a "$LOG"
while pgrep -f "scripts/0[345]_run" > /dev/null 2>&1; do
    sleep 10
    echo "[$(date)] ... still running: $(pgrep -f 'scripts/0[345]_run' | tr '\n' ' ')" | tee -a "$LOG"
done
echo "[$(date)] All experiment scripts finished." | tee -a "$LOG"

# --- Run ablation matrix ---
echo "[$(date)] Starting ablation matrix (script 05)..." | tee -a "$LOG"
python3 scripts/05_run_ablation.py 2>&1 | tee -a "$LOG"
echo "[$(date)] Ablation done." | tee -a "$LOG"

# --- Run evaluation ---
echo "[$(date)] Starting evaluation (script 06)..." | tee -a "$LOG"
python3 scripts/06_eval.py 2>&1 | tee -a "$LOG"
echo "[$(date)] Evaluation done." | tee -a "$LOG"

# --- Show results ---
echo "[$(date)] === MAIN TABLE ===" | tee -a "$LOG"
cat experiments/results/main_table.csv | tee -a "$LOG"
echo "" | tee -a "$LOG"
echo "[$(date)] === SIGNIFICANCE ===" | tee -a "$LOG"
cat experiments/results/significance.json | tee -a "$LOG"
echo "" | tee -a "$LOG"

# --- Git commit + push ---
echo "[$(date)] Pushing to GitHub..." | tee -a "$LOG"
git add -A
git commit -m "Add experiment results: baselines + KG-SCoRE + ablation + evaluation

- ComplEx KG completion trained (MRR=$(grep -o 'mrr.*' experiments/results/significance.json | head -1 | grep -o '[0-9.]*' | head -1))
- Baselines: vanilla_llm, bm25_rag, dense_rag, tog
- KG-SCoRE full pipeline with co-refinement + faithfulness
- Ablation matrix: raw_kg, +llm, +learned, full, no_kg, no_faith
- Main table + significance tests + figures

Generated by auto_pipeline.sh" 2>&1 | tee -a "$LOG"

if [ -n "$GH_TOKEN" ]; then
    git push "https://${GH_USER}:${GH_TOKEN}@github.com/${GH_USER}/KDD2027_LLM.git" main 2>&1 | tee -a "$LOG"
    # remove token from remote
    git remote set-url origin https://github.com/${GH_USER}/KDD2027_LLM.git
else
    git push origin main 2>&1 | tee -a "$LOG"
fi

echo "[$(date)] === PIPELINE COMPLETE ===" | tee -a "$LOG"
echo "[$(date)] Results pushed to GitHub." | tee -a "$LOG"
